name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - hydra-core
  - pip
  - jupyterlab
  - scikit-learn=1.3.2
  - matplotlib
  - pydantic
  - pytest
  - scipy
  - pip:
      - mlflow
      - wandb
